ln -f /u/dsprofes/laboral/cal/i_04.cal
ln -f /u/dsprofes/laboral/cal/i_05.cal
ln -f /u/dsprofes/laboral/cal/i_06.cal
ln -f /u/dsprofes/laboral/cal/i_14.cal
ln -f /u/dsprofes/laboral/cal/i_1tc21.cal
ln -f /u/dsprofes/laboral/cal/i_1ytc1.cal
ln -f /u/dsprofes/laboral/cal/i_2ytc1.cal
ln -f /u/dsprofes/laboral/cal/i_2ytc2.cal
ln -f /u/dsprofes/laboral/cal/i_3ytc1.cal
ln -f /u/dsprofes/laboral/cal/i_87.cal
ln -f /u/dsprofes/laboral/cal/i_athis.cal
ln -f /u/dsprofes/laboral/cal/i_auxil.cal
ln -f /u/dsprofes/laboral/cal/i_busqu.cal
ln -f /u/dsprofes/laboral/cal/i_camver.cal
ln -f /u/dsprofes/laboral/cal/i_comun.cal
ln -f /u/dsprofes/laboral/cal/i_conli.cal
ln -f /u/dsprofes/laboral/cal/i_coptra.cal
ln -f /u/dsprofes/laboral/cal/i_cuadr.cal
ln -f /u/dsprofes/laboral/cal/i_fiche.cal
ln -f /u/dsprofes/laboral/cal/i_finiq.cal
ln -f /u/dsprofes/laboral/cal/i_ireno.cal
ln -f /u/dsprofes/laboral/cal/i_logo.cal
ln -f /u/dsprofes/laboral/cal/i_manca.cal
ln -f /u/dsprofes/laboral/cal/i_no3145.cal
ln -f /u/dsprofes/laboral/cal/i_nomcr.cal
ln -f /u/dsprofes/laboral/cal/i_nomre2.cal
ln -f /u/dsprofes/laboral/cal/i_pdfrec.cal
ln -f /u/dsprofes/laboral/cal/i_petip.cal
ln -f /u/dsprofes/laboral/cal/i_re3145.cal
ln -f /u/dsprofes/laboral/cal/i_reco1.cal
ln -f /u/dsprofes/laboral/cal/i_reco2.cal
ln -f /u/dsprofes/laboral/cal/i_recoa.cal
ln -f /u/dsprofes/laboral/cal/i_recog.cal
ln -f /u/dsprofes/laboral/cal/i_sepnom.cal
ln -f /u/dsprofes/laboral/cal/i_sreci.cal
ln -f /u/dsprofes/laboral/cal/i_tempo.cal
ln -f /u/dsprofes/laboral/cal/i_varia.cal
ln -f /u/dsprofes/laboral/cal/i_visado.cal
ln -f /u/dsprofes/laboral/cal/i_yreci.cal
ln -f /u/dsprofes/laboral/cal/i_yreno.cal
ln -f /u/dsprofes/laboral/cal/nomcal_1.cal
ln -f /u/dsprofes/laboral/cal/nomcal_2.cal
ln -f /u/dsprofes/laboral/cal/nomcal_3.cal
ln -f /u/dsprofes/laboral/cal/nomcal_4.cal
ln -f /u/dsprofes/laboral/cal/nomcal_5.cal
ln -f /u/dsprofes/laboral/cal/pastil_i.cal
ln -f /u/dsprofes/laboral/cal/i_varglo.cal
