CalculoDNI,zcalcplb
CalculoDC,zcalcplb
Encripta,zcalcplb
LocalizaAcrobat,zcalcplb
PonRaros,zcalcplb

MiraDirectorios,plbwords
EnviaFicheroSinMD5,plbwords
EnviaFicheroConMD5,plbwords
ComprimeFichero,plbwords
DescomprimeFichero,plbwords
EditaModoExterno,plbwords
RecibeFichero,plbwords
MiraLogos,plbwords
QuitaRaros,plbwords
SeparaNombre,plbwords
SeparaImporte,plbwords
AbreWordExterno,plbwords
SacaFecha,plbwords
CopiaRTF,plbwords

