SeparaImporte,zdatoplb
CargaTabla,zdatoplb
SacaTabla,zdatoplb
CompruebaTabla,zdatoplb
FinTabla,zdatoplb
LeeUnidadBasico,zdatoplb
QuitaBotonSalir,zdatoplb
PonBotonSalir,zdatoplb
QuitaBtnSalir,zdatoplb
PonBtnSalir,zdatoplb
CargaColores,zdatoplb
;
CalculoDNI,dsaw9999
;
LeePoblacion,zdatoadi
;
CalcuIBAN,plbbanco
CalculoDC,plbbanco
